accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, \
    AccountDeleteView  # 지정한 뷰 함수 가져오기

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'), # 경로 지정
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), # detail은 특정 유저의 정보를 봐야 함 - 계정의 ID(pk)가 필요함, <int:pk> - pk라는 이름의 int 정보를 받겠다.
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

ostus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media 파일

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm): # UpdateView(정보수정) 전용 폼 / UserCreationForm을 상속받음
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) # 상속 받은 그대로 사용함
        self.fields['username'].disabled = True # ID 입력 칸만 비활성화 시킴 - 회원정보 수정 시 ID는 변경하지 않게 하기 위함

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorator import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required] # decorater 배열

@login_required # 로그인 인증 decorator - 함수형 뷰 전용
def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get('hello_world_input')  # POST 요청의 폼에서 hello_world_input인 데이터를 가져와라

        new_hello_world = HelloWorld()  # HelloWorld 객체(모델) 생성
        new_hello_world.text = temp  # temp를 text로
        new_hello_world.save()  # 저장

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
        # POST 요청에 의한 응답으로 text에 값을 보냄
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})




class AccountCreateView(CreateView): # Create
    model = User # 장고에서 제공하는 User 객체
    form_class = UserCreationForm # 폼
    success_url = reverse_lazy('accountapp:hello_world') # 이 계정을 만드는데 성공했을 경우 돌아갈 url
    template_name = 'accountapp/create.html' # 회원가입 프론트

class AccountDetailView(DetailView, MultipleObjectMixin): # Read - Detail, Multiple - 프로필 아래 자신이 작성한 article을 보여주기 위해 다른 오브젝트를 출력하기 위함
    model = User
    context_object_name = 'target_user' # detail 페이지에서 user의 정보를 출력하면 무조건 나의 정보만 띄운다. 즉 다른 사람의 페이지로 들어가도 내정보가 나옴 / 따라서 이렇게 target_user를 설정
    template_name = 'accountapp/detail.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

@method_decorator(has_ownership, 'get') # 클래스형 뷰에 인증 decorator을 사용하기 위해서 method_decorator를 사용해야 함
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView): # Update - Create와 똑같다.
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm # Update 전용 폼으로 사용
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %} <!-- 라이브러리를 통해 폼 꾸미기 -->

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4"> <!-- marginbottom 4배 -->
            <h4>SignUp</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4"> <!-- marginbottom 4배 -->
            <h4>Delete</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

            {% if target_user.profile %} <!-- 타겟 유저가 Profile을 가지고 있다면 username을 출력 -->

            <img src="{{ target_user.profile.image.url }}" alt="" style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">

            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.username }}
                    {% if target_user == user %} <!-- 접속한 user와 타겟 user가 같은 경우에만 edit 버튼 보임 -->
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"> <!-- 프로필 Update 버튼 -->
                        edit
                    </a>
                    {% endif %}
            </h2>

            <h5 style="margin-bottom: 3rem;"> {{ target_user.profile.message }} </h5>

            {% else %} <!-- 없다면 Profile을 만드는 페이지로 이동하는 버튼 출력 -->
                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: 'NanumSquareB'">
                        Create Profile
                    </h2>
                </a>
                {% else %}
                <h2>닉네임 미설정</h2>
                {% endif %}
            {% endif %}


            {% if target_user == user %} <!-- 지금 접속한 유저와 타겟 유저가 같은 경우 정보 수정 버튼이 보임 -->
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>Change Info</p>
            </a>
            <a href="{% url 'accountapp:delete' pk=user.pk %}">
                <p>Delete</p>
            </a>
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>

    </div>
{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}
    <div style=" border-radius: 1rem; margin: 2rem; text-align: center">

        <h1 style="font-family: 'lobster', cursive;">Hello World LIST!</h1>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input"/> <!-- 이 클래스는 bootstrap에서 가져옴 -->
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST"/>
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %} <!-- 라이브러리를 통해 폼 꾸미기 -->

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <!-- {{ form }} --> <!-- 클래스 뷰에서 지정한 폼클래스 -->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3"> <!-- rounded-pill - 둥글게 / col-6 - 너비(12면 100퍼센트) / mt-3 - margintop이 3배 -->
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %} <!-- 라이브러리를 통해 폼 꾸미기 -->

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4"> <!-- marginbottom 4배 -->
            <h4>Change Info</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}