accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, \
    AccountDeleteView  # 지정한 뷰 함수 가져오기

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'), # 경로 지정
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), # detail은 특정 유저의 정보를 봐야 함 - 계정의 ID(pk)가 필요함, <int:pk> - pk라는 이름의 int 정보를 받겠다.
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

ostus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media 파일

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectDetailView, ProjectCreateView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('create/', ProjectCreateView.as_view(), name='create'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">
    {% include 'header.html' %}

    <hr>

    {% block content %} <!-- 블록으로 지정 - 앱마다 수정해서 사용 가능함 -->
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span>  |
        <span>제휴문의</span>  |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %} <!-- static을 사용하기 위함 -->

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <!-- 디바이스에 맞게 크기를 맞춰서 페이지가 보임 -->
    <title>Title</title>

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 class="pragmatic_logo">Pragmatic</h1>
    </div>
    <div class="pragmatic_header_navbar">
        <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
            <span>Subscription</span>
        </a>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <!-- 유저가 로그인되어 있지 않으면 login버튼을 띄움, 버튼 클릭 시 login 페이지로 이동된다. get 요청으로 next를 지정하여 리다이렉트 시 원래 있었던 페이지로 돌아옴 -->
            <span>Login</span>
        </a>
        <a href="{% url 'accountapp:create' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav"> <!-- 지금 접속한 유저의 pk값을 넣어준다. -->
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <span>Logout</span>
        </a>
        {% endif %}
    </div>
</div>